version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src  # For hot reload during development
      - ./checkpoints:/app/checkpoints  # For model persistence
      - ./data:/app/data  # For dataset persistence
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: bash -c "cd src && uvicorn app:app --host 0.0.0.0 --port 8080 --reload"
